### ISSUE TITLE
Impact System | v.0.1.6

### ISSUE THREAD

**Issue by cellaneza** [CoolCoderMan281/Stumpy-Road#14]
![image](https://github.com/CoolCoderMan281/Stumpy-Road/assets/123773582/4dcb5e02-ab27-4595-8963-e6de50882418)

📝 impactTime needs a slider! 
"Cheerio that."
- CoolCoderMan281, 12/5/2023

**Comment by CoolCoderMan281** [comment]
In 0.2.3
