### ISSUE TITLE
Scoring System | v.0.2.0

### ISSUE THREAD

**Issue by cellaneza** [CoolCoderMan281/Stumpy-Road#15]
![image](https://github.com/CoolCoderMan281/Stumpy-Road/assets/123773582/27686585-14a8-423d-ae9c-46dbc56cb472)

📝 You can either base this off the difficultyTick or really futureproof this and make a separate variable called "scoringSpeed" and make it into it's own slider so that we can alter how fast the player should get points in accordance with the gameplay.

**Comment by CoolCoderMan281** [comment]
In 0.2.1
