### ISSUE TITLE
Game Setup | v.0.2.3

### ISSUE THREAD

**Issue by cellaneza** [CoolCoderMan281/Stumpy-Road#24]
Make sure all the game's initialized variables start with the values defined [here!](https://docs.google.com/spreadsheets/d/14V_3rfqrQPu_z4S7nKaWwPx2AoVO-aKKMBtw14Q1OdY/edit#gid=0)

= Make sure the final version of the game is named "Road Kill"
= Remove obstacle spawning during Rage Mode.
= ADD CREDITS!!

![image](https://github.com/CoolCoderMan281/Stumpy-Road/assets/123773582/7b0b3dd7-9697-44ee-8578-5859e366e318)

**Comment by CoolCoderMan281** [comment]
In as of 0.2.4 which I'll be building soon
