### ISSUE TITLE
⚙️ Speed Boost System | v.0.1.4

### ISSUE THREAD

**Issue by cellaneza** [CoolCoderMan281/Stumpy-Road#5]
📝 Hey, I won't be able to give in-depth system explanations or anything because something's come up that'll keep me busy throughout the day. I'm very sorry, please ask me if there's anything you need clarification on!

⚙️ This system should make it look like the car is moving faster when the player presses "W" or the "Up Arrow Key"

![image](https://github.com/CoolCoderMan281/Stumpy-Road/assets/123773582/d4044b76-5393-4541-ae3b-970235bd90be)

(Here's the link to the Miro Board in case the image doesn't upload properly, it should be labeled under "BOOST SYSTEM")
[https://miro.com/app/board/uXjVNSw5WwE=/](url)

**Comment by CoolCoderMan281** [comment]
Resolved in 0.1.5, smoothing for this is currently on hold, until I get final numbers. Use slider Boost Buff.
