### ISSUE TITLE
⚙️ Difficulty Progression System | v.0.1.6

### ISSUE THREAD

**Issue by cellaneza** [CoolCoderMan281/Stumpy-Road#8]
![image](https://github.com/CoolCoderMan281/Stumpy-Road/assets/123773582/f6971981-f75e-4460-9c7b-76fb7ca66017)

📝 Basically, the speed will get progressively faster in a linear trend. I wanted to actually give a better equation, but considering how tight the deadline is and how a better equation may take more time to test, this should work just fine.

**Comment by CoolCoderMan281** [comment]
Resolved in #0.1.8 which isn't released yet but its done.
